
###### 도서 쇼핑몰 프로젝트 테이블 생성 SQL #####

### 생성 예상 테이블 ###
#1. 회원 정보 테이블 SHOP_MEMBER
#2. 도서 카테고리 테이블 BOOK_CATEGORY
#3. 도서 정보 테이블 SHOP_BOOK
#4. 장바구니 테이블 SHOP_CART
#5. 구매 정보 테이블 SHOP_BUY

# 회원정보 테이블 생성문
CREATE TABLE SHOP_MEMBER (
	MEM_EMAIL VARCHAR(50) PRIMARY KEY 
	, MEM_PW VARCHAR(50) NOT NULL 
	, MEM_NAME VARCHAR(30) NOT NULL 
	, MEM_TEL VARCHAR(15) NOT NULL UNIQUE  #'010-1111-2222'
	, MEM_ADDR VARCHAR(50)
	, ADDR_DETAIL VARCHAR(100)
	, IS_USING VARCHAR(10) DEFAULT 'Y'  #'Y' : 사용중, 'N' : 사용 안 함
	, MEM_ROLE VARCHAR(20) DEFAULT 'USER' #USER:회원, MANAGER:쇼핑몰 운영자, ADMIN:관리자
	, JOIN_DATE DATETIME DEFAULT SYSDATE()
);


# 도서 카테고리 정보
CREATE TABLE BOOK_CATEGORY (
	CATE_NUM INT PRIMARY KEY AUTO_INCREMENT
	, CATE_NAME VARCHAR(20) NOT NULL UNIQUE 
);

# 도서 카테고리 기본 데이터
INSERT INTO BOOK_CATEGORY VALUES (1,'IT/인터넷');
INSERT INTO BOOK_CATEGORY VALUES (2,'자기계발');
INSERT INTO BOOK_CATEGORY VALUES (3,'소설/에세이');


# 도서 정보 테이블
CREATE TABLE SHOP_BOOK (
	BOOK_NUM INT PRIMARY KEY AUTO_INCREMENT
	, BOOK_TITLE VARCHAR(30) NOT NULL
	, AUTHOR VARCHAR(20) NOT NULL
	, BOOK_PRICE INT NOT NULL
	, BOOK_STOCK INT DEFAULT 10
	, BOOK_INTRO VARCHAR(200)
	, PUBLISH_DATE DATETIME
	, CATE_NUM INT NOT NULL REFERENCES BOOK_CATEGORY (CATE_NUM)
);

# 도서 이미지 정보 테이블
CREATE TABLE BOOK_IMG(
	IMG_NUM INT PRIMARY KEY AUTO_INCREMENT
	, ORIGIN_FILE_NAME VARCHAR(100)  # 원본 파일명
	, UPLOAD_FILE_NAME VARCHAR(100)  # 첨부된 파일명
	, IS_MAIN VARCHAR(1) NOT NULL  #대표 이미지 여부(Y,N)
	, BOOK_NUM INT NOT NULL REFERENCES SHOP_BOOK (BOOK_NUM) ON DELETE CASCADE
	# ON DELETE CASCADE : BOOK_NUM을 지우면(도서를 지우면) 해당 컬럼이 같이 삭제됨(이미지도 같이 삭제)
)





UPDATE SHOP_MEMBER
SET 
	MEM_EMAIL = 'manager'
	, MEM_PW = '1111'
	, MEM_ROLE = 'MANAGER'
WHERE MEM_EMAIL = 'mm@naver.com';

# 이미지
# 도서번호, 도서명, 도서가격, 해당 도서의 첨부된 파일 조회
SELECT
	B.BOOK_NUM
	, BOOK_TITLE
	, BOOK_PRICE
	, UPLOAD_FILE_NAME
FROM SHOP_BOOK B INNER JOIN BOOK_IMG I
ON B.BOOK_NUM = I.BOOK_NUM;
-- WHERE IS_MAIN = 'Y';


CREATE TABLE SHOP_CART (
	CART_NUM INT PRIMARY KEY AUTO_INCREMENT 							#장바구니번호
	, BOOK_NUM INT NOT NULL REFERENCES SHOP_BOOK (BOOK_NUM) ON DELETE CASCADE  #상품번호 
	, CART_CNT INT NOT NULL 											#장바구니에 담은 도서 수량 #장바구니에 담은 수량
	, MEM_EMAIL VARCHAR(50) NOT NULL REFERENCES SHOP_MEMBER (MEM_EMAIL) #장바구니 주인 Email 
	, CART_DATE DATETIME DEFAULT SYSDATE() 								#장바구니에 담은 날짜
);

SELECT * FROM SHOP_CART ORDER BY CART_DATE DESC;   #장바구니
SELECT * FROM SHOP_MEMBER; 						#고객정보
SELECT * FROM SHOP_BOOK;   						#도서정보
SELECT * FROM BOOK_CATEGORY; 					#카테고리3개
SELECT * FROM BOOK_IMG;	   						#도서이미지
SELECT * FROM SHOP_BUY;							#구매정보
SELECT * FROM BUY_DETAIL;						#구매정보(상세)


# 구매 정보 테이블
CREATE TABLE SHOP_BUY (
	BUY_NUM INT PRIMARY KEY AUTO_INCREMENT 					#구매번호
	, BUY_PRICE INT NOT NULL 								#총구매금액
	, MEM_EMAIL VARCHAR(50) NOT NULL REFERENCES SHOP_MEMBER (MEM_EMAIL) #구매자 Email
	, BUY_DATE DATETIME DEFAULT SYSDATE() 					#구매일
);

# 구매 상세 정보 테이블
CREATE TABLE BUY_DETAIL (
	BUY_DETAIL_NUM INT PRIMARY KEY AUTO_INCREMENT 			#구매 상세 번호
	, BOOK_NUM INT NOT NULL REFERENCES SHOP_BOOK (BOOK_NUM) #상품번호
	, BUY_CNT INT NOT NULL 									#구매수량
	, BUY_NUM INT NOT NULL  REFERENCES SHOP_BUY (BUY_NUM) 	#구매번호
);







# 1. 오늘과 이 달의 주문건수 및 매출금액 조회
SELECT 
	(
		SELECT COUNT(BUY_NUM)
		FROM SHOP_BUY
		WHERE DATE(BUY_DATE) = CURRENT_DATE()
	) AS SALE_CNT_TODAY, 
	(
		SELECT COUNT(BUY_NUM)
		FROM SHOP_BUY
		WHERE DATE(BUY_DATE) 
		BETWEEN CONCAT(TO_CHAR(CURRENT_DATE(), 'YYYY-MM'), '-01') 
		AND CURRENT_DATE()
	) AS SALE_CNT_MONTH, 
	(
		SELECT NVL(SUM(BUY_PRICE),0)
		FROM SHOP_BUY
		WHERE DATE(BUY_DATE) = CURRENT_DATE()
	) AS SALE_TODAY, 
	(
		SELECT NVL(SUM(BUY_PRICE),0)
		FROM SHOP_BUY
		WHERE DATE(BUY_DATE) 
		BETWEEN CONCAT(TO_CHAR(CURRENT_DATE(), 'YYYY-MM'), '-01') 
		AND CURRENT_DATE()
	) AS SALE_MONTH;


# 2. 구매랭킹
SELECT MEM_EMAIL
	, COUNT(BUY_NUM) SALE_CNT_PER_MEMBER
	, SUM(BUY_PRICE) SALE_PER_MEMBER
FROM SHOP_BUY
GROUP BY MEM_EMAIL
ORDER BY SALE_PER_MEMBER DESC
LIMIT 5;

# 3. 인서 도서 랭킹
SELECT D.BOOK_NUM, SUM(BUY_CNT) TOTAL_BUY_CNT, BOOK_TITLE, AUTHOR
FROM BUY_DETAIL D, SHOP_BOOK B
WHERE D.BOOK_NUM = B.BOOK_NUM
GROUP BY D.BOOK_NUM
ORDER BY TOTAL_BUY_CNT DESC, BOOK_TITLE ASC
LIMIT  5;

# 4. 차트 데이터 조회
SELECT ADDDATE(CURRENT_DATE(), -3)
	, (SELECT NVL(SUM(BUY_PRICE), 0) 
			FROM SHOP_BUY
			WHERE DATE(BUY_DATE) = ADDDATE(CURRENT_DATE(), -3)) AS SALE
UNION ALL
SELECT ADDDATE(CURRENT_DATE(), -2)
	, (SELECT NVL(SUM(BUY_PRICE), 0) 
			FROM SHOP_BUY
			WHERE DATE(BUY_DATE) = ADDDATE(CURRENT_DATE(), -2)) AS SALE
UNION ALL
SELECT ADDDATE(CURRENT_DATE(), -1)
	, (SELECT NVL(SUM(BUY_PRICE), 0) 
			FROM SHOP_BUY
			WHERE DATE(BUY_DATE) = ADDDATE(CURRENT_DATE(), -1)) AS SALE
UNION ALL
SELECT ADDDATE(CURRENT_DATE(), -0)
	, (SELECT NVL(SUM(BUY_PRICE), 0)   
			FROM SHOP_BUY
			WHERE DATE(BUY_DATE) = ADDDATE(CURRENT_DATE(), -0)) AS SALE ;



































